name: Publish packages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  pages: write
  id-token: write

jobs:
  publish-packages:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com/'
          always-auth: true

      - name: Install dependencies
        run: pnpm install

      - name: Override .npmrc authentication
        run: |
          echo "@angular-utilities:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      # TODO Build and publish all publishable libraries
      # - run: nx run-many --target=build --all
      # - run: nx run-many --target=publish --all

      - name: Add NX to PATH
        run: echo "export PATH=$(pnpm root)/.bin:\$PATH" >> $GITHUB_ENV

      - name: Check for affected libraries
        id: affected
        run: |
          source $GITHUB_ENV
          AFFECTED_LIBS=$(npx nx show projects --affected --base=origin/main --head=HEAD --type lib)
          echo "AFFECTED_LIBS=$AFFECTED_LIBS" >> $GITHUB_ENV

      - name: Auto bump version if affected
        if: contains(env.AFFECTED_LIBS, 'angular-material')
        run: |
          pnpm nx run angular-material:version --no-push --skip-project-changelog
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore(release): version bump [skip ci]" || echo "No changes to commit"

      - name: Build and Publish If Affected
        if: contains(env.AFFECTED_LIBS, 'angular-material')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm build angular-material
          pnpm publish --no-git-checks --access public || (cat /home/runner/.npm/_logs/* && exit 1)
