name: Publish packages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  pages: write
  id-token: write

jobs:
  publish-packages:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com/'
          always-auth: true

      - name: Install dependencies
        run: pnpm install

      - name: Override .npmrc authentication
        run: |
          echo "@angular-utilities:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      # TODO Build and publish all publishable libraries
      # - run: nx run-many --target=build --all
      # - run: nx run-many --target=publish --all

      - name: Check for affected libraries
        id: affected
        run: |
          echo "AFFECTED_LIBS=$(nx affected:libs --plain)" >> $GITHUB_ENV

      - name: Build and Publish If Affected
        if: contains(env.AFFECTED_LIBS, 'angular-material')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # working-directory: dist/libs/ui/angular-material
        run: |
          pnpm publish --no-git-checks --access public || (cat /home/runner/.npm/_logs/* && exit 1)
